name: Tests
on:
  push:

  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate set "debug_enabled"'
        type: boolean
        required: false
        default: false

defaults:
  run:
    shell: bash

env:
  BUILDKIT_PROGRESS: plain
  DDEV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Run basic docker container
        run: |
          docker run --rm debian:bookworm bash -c 'arch && cat /etc/*release*'


